# Default values for host-check-app.
#
# There are two required fields which have no defaults and must
# be specified for all installations:
# - image.repository
# - image.tag

# Image configuration
image:
  # Repository for the container image (required).
  #repository: ""
  # Image tag (required).
  #tag: ""
  # Pull policy for images.
  # One of "IfNotPresent", "Always", or "Never"
  # See https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
  pullPolicy: IfNotPresent
  # Image pull secrets.
  # See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  pullSecrets: []

# Host-check-app configuration
# List of platforms to run host-check-app for.
platforms: []

# Location control for the host-check-app Pod.
# Standard K8s configuration, more information available at:
# https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
# Node labels for pod assignment.
nodeSelector: {}
# List of node taints to tolerate.
tolerations: []
# Affinity for pod assignment.
affinity: {}
