#!/bin/bash

set -e


# function cleanup()
# {
#     echo
#     echo "Cleaning up..."
#     if [[ -d $TMP_VENV ]]; then
#         rm -r "$TMP_VENV"
#     fi
# }

# trap cleanup EXIT

# @@@ Needed
# shellcheck
# helm-sa
# helm ut


#=====================================================
# Run checks
#=====================================================

FAILURES=0

# Check version incerment
python3 -m pip install --upgrade pip
python3 -m pip install PyYAML

./scripts/check-dependency-version-increment

# chart-testing (list-changed)
DEFAULT_BRANCH="main"
changed=$(ct list-changed --target-branch $DEFAULT_BRANCH)
    if [[ -n "$changed" ]]; then
        echo "::set-output name=changed::true"
    fi

# chart-testing (lint)
ct lint --config .github/config/ct.yml --target-branch $DEFAULT_BRANCH

# chart-testing (check-version-increment)
ct lint --config .github/config/ct-version-increment.yml --target-branch $DEFAULT_BRANCH


# echo
# echo "Running shellcheck..."
# if ! shellcheck scripts/{apply-bugfixes,launch-xrd}; then
#     echo "Shellcheck failed, check output and fix issues." >&2
#     FAILURES=$((FAILURES+1))
# fi

# echo
# echo "Running tests..."
# if ! pytest; then
#     echo "Tests failed, check output and fix issues." >&2
#     FAILURES=$((FAILURES+1))
# fi


#=====================================================
# Final steps
#=====================================================

echo
if ((FAILURES > 0)); then
    echo "ERROR: There were $FAILURES failures"
    exit 1
else
    echo "SUCCESS: All passed!"
    exit 0
fi