name: commit-checks

on:
  pull_request:
    branches:
      - 'main'
      - 'preview-[0-9]+\.[0-9]+\.[0-9]+'
    paths-ignore:
      - '.gitignore'
      - '*.md'
  push:
    branches:
      - 'main'
      - 'gh-actions*'

jobs:
  all_tests:
    runs-on: ubuntu-latest
    name: 'commit-checks'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - uses: azure/setup-helm@v3
        with:
          version: '3.10.0'

      - uses: helm/chart-testing-action@v2.3.1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: "tests"
          load: true

      - name: Run all tests
        run: scripts/commit-check-new
