name: commit-checks

on:
  pull_request:
    branches:
      - 'main'
      - 'preview-[0-9]+\.[0-9]+\.[0-9]+'
    paths-ignore:
      - '.gitignore'
      - '*.md'
  push:
    branches:
      - 'main'
      - 'gh-actions*'

jobs:
  all_tests:
    runs-on: ubuntu-latest
    name: 'commit-checks'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run all tests
        run: scripts/commit-check
