name: static-analysis

on:
  pull_request:
    branches:
      - 'main'
      - 'preview-[0-9]+\.[0-9]+\.[0-9]+'
    paths-ignore:
      - '.gitignore'
      - '*.md'
  push:
    branches:
      - 'gh-actions*'

jobs:
  helm:
    runs-on: ubuntu-latest
    name: 'helm-sa'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - uses: azure/setup-helm@v3
        with:
          version: '3.10.0'

      - uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
              echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

  shellcheck:
    runs-on: ubuntu-latest
    name: 'bash-sa (shellcheck)'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: 'scripts/'
